INSERT INTO item (name, has_quantity) VALUES
('Fuel', 1),
('Credits', 1),
('Basic Clothes', 0),
('Revolver', 0),
('Rifle', 0),
('Pistol', 0),
('Clip', 1),
('Ammo', 1),
('Flak Jacket', 0),
('Utility Knife', 0),
('Advanced Medical Equipment', 0),
('Food Rations', 0),
('Torch', 0),
('Bag', 0),
('Spare Battery', 0),
('Communications Device', 0),
('Sniper', 0),
('Combat Knife', 0),
('Climbing Gear', 0),
('Rope', 0),
('Duelling Pistol', 0),
('Ornate Clothes', 0),
('Executioner Pistol', 0),
('Full Metal Helmet', 0),
('Full Metal Armor', 0),
('Sword', 0),
('Communications Earpiece', 0),
('Backpack', 0),
('Basic Medical Equipment', 0),
('Gas Mask', 0);